### ISSUE TITLE
Does not work with M5Stack boards package since version 2.0.1

### ISSUE THREAD

**Issue by proostas** [m5stack/M5-DLight#1]
The example hangs at the line:
`lux = sensor.getLUX();`

Probably it is something to do with TwoWire in the package because there appear a warning about an ambiguous function call: 
`bool begin(int sda=-1, int scl=-1, uint32_t frequency=0);
bool begin(uint8_t slaveAddr, int sda=-1, int scl=-1, uint32_t frequency=0);
`

Changing line 46 in M5_BH1750FVI.cpp to `_wire->begin((int)_sda, (int)_scl, _freq);` did not help.

**Comment by motoishmz** [comment]
Same here, my M5StickC Plus also hangs at `lux = sensor.getLUX();` 
esp32 version: `2.0.2`

**Comment by nya3jp** [comment]
I've just sent a PR to fix this: #2.

**Comment by imliubo** [comment]
Fix by this PR #2 , thanks @nya3jp contribute.
