### ISSUE TITLE
Accessing the sensor in micropython?

### ISSUE THREAD

**Issue by wilsonfan** [m5stack/M5-DLight#4]
Hi there,

Just want to ask if there is a simple / example way to access the light sensor via micropython? Is there some library I can use for this or you have any tips to make this work? I am trying to run this attached to the atom lite.

Thank you!

**Comment by TinyuZhao** [comment]
I have found some MicroPython libraries for the BH1750FVI that you can try to use on your device
https://github.com/PinkInk/upylib/tree/master/bh1750
https://github.com/catdog2/mpy_bh1750fvi_esp8266
In addition, we also offer a simple and easy graphical programming [UIFLOW](https://docs.m5stack.com/en/quick_start/atom/uiflow) to adapt our accessories, you can try it out.
