### ISSUE TITLE
Request to publish version 0.0.2 to PlatformIO

### ISSUE THREAD

**Issue by matthewhadley** [m5stack/M5-DLight#5]
```
$ pio pkg search M5-DLight
Found 1 packages (page 1 of 1)

m5stack/M5-DLight
Library • 0.0.1 • Published on Fri Jul  8 05:13:20 2022
Library for M5Stack Unit&Hat DLight
```

Can you please publish version `0.0.2` to PlatformIO?

https://docs.platformio.org/en/latest/core/userguide/pkg/cmd_publish.html#cmd-pkg-publish

**Comment by TinyuZhao** [comment]
Thank you for your feedback, I am contacting the PlatformIO administrator to solve this problem, it seems to be a bug.
![](https://user-images.githubusercontent.com/44396641/227774220-e8930948-afd4-4f79-bd63-9334f98460a4.png)

**Comment by matthewhadley** [comment]
Thank you for looking into it and for this library!

Until it's resolved I have found that specifying the branch directly as a dependency will pull in the current `0.0.2` code :

(inside platformio.ini)
```
lib_deps =
    https://github.com/m5stack/M5-DLight#master
```

**Comment by ivankravets** [comment]
The tag `0.0.2` contains broken manifests. They still point to the `0.0.1` version. See https://github.com/m5stack/M5-DLight/tree/0.0.2

Please update the "version" field to 0.0.3 in `library.json` and `library.properties`,  and AFTER please create the new tag `0.0.3`.

Thanks in advance.

**Comment by TinyuZhao** [comment]
> The tag `0.0.2` contains broken manifests. They still point to the `0.0.1` version. See https://github.com/m5stack/M5-DLight/tree/0.0.2
> 
> Please update the "version" field to 0.0.3 in `library.json` and `library.properties`, and AFTER please create the new tag `0.0.3`.
> 
> Thanks in advance.

<img width="779" alt="image" src="https://github.com/m5stack/M5-DLight/assets/44396641/5f28ae23-ddd0-4ee9-8735-bd91fc332c8a">
@ivankravets I've released version 0.0.3 but I still don't have a search in the lib and when I try to do it manually for 0.03 I can't set the repository owner to m5stack.

**Comment by ivankravets** [comment]
It seems it was automatically updated https://registry.platformio.org/libraries/m5stack/M5-DLight

**Comment by TinyuZhao** [comment]
<img width="1627" alt="image" src="https://github.com/m5stack/M5-DLight/assets/44396641/9a48c98c-c080-403c-a594-1cce2c93716d">
