### ISSUE TITLE
no conversion to raw lux

### ISSUE THREAD

**Issue by lbuque** [m5stack/M5-DLight#6]
The datasheet states that raw lux needs to be converted, but the code does not.

![image](https://user-images.githubusercontent.com/46518962/236725790-b2da006b-5631-45e8-b235-7b2392b6f4ff.png)

**Comment by TinyuZhao** [comment]
[Thank you.](https://github.com/m5stack/M5-DLight/blob/24ffd7645c77b3aeae2a9be4194f5df086396f43/src/M5_DLight.cpp#L46)
